// The Archive Encyclopedia — manuscriptContentBlackNative.ts
// By LaDarious Strickland © 2026
// Chapter: Black Native American Identity — The Suppressed History

export interface ChapterContent {
  slug: string;
  fullText: string[];
  pullQuote?: { text: string; attribution: string };
  didYouKnow?: string;
  keyDocuments?: string[];
}

export const BLACK_NATIVE_CONTENT: Record<string, ChapterContent> = {
  'black-native-american-identity': {
    slug: 'black-native-american-identity',
    fullText: [
      'The central question of this encyclopedia begins not in Africa, not in Europe, but here — on this land. The question is not merely who was enslaved, but who was already here when the ships arrived. The documented historical record, when read without the filter of the racial categories that were imposed upon it, reveals a history that mainstream scholarship has been slow to confront: many of the people classified as "Negro," "Black," and "Colored" in American census records, slave manifests, and Freedmen enrollment rolls were not exclusively of African descent. They were, in significant numbers, Indigenous people who had been captured in colonial wars, stripped of their tribal names, and reclassified under administrative labels designed to erase their land claims, their sovereignty, and their identity.',

      'This is not a theory. It is documented in the primary sources that colonial administrators themselves created. The evidence exists in Virginia county records, South Carolina census rolls, the Dawes Commission enrollment files at the National Archives, and the United States Supreme Court. The work of this chapter is to lay that evidence before the reader, in proper evidentiary order, and to let the documents speak.',

      '— I. THE COLONIAL RENAMING MACHINE —',

      'The process of renaming began with military defeat. Between 1711 and 1717, two of the most significant colonial wars in the American Southeast — the Tuscarora War (1711–1715) and the Yamasee War (1715–1717) — resulted in the capture and enslavement of thousands of Indigenous people. The Tuscarora of North Carolina were nearly destroyed as a nation. The Yamasee of South Carolina, who had been trading partners with the English for decades, rose in a coalition with the Creek, Cherokee, Catawba, and other nations in what was the most serious threat to English colonial power in the Southeast. When the coalition was defeated, the survivors were sold into slavery.',

      'The 1720s Carolina census recorded approximately 1,500 enslaved American Indians within a total colonial population of 17,000. These individuals did not appear in the records as Tuscarora or Yamasee. They appeared under English names — classical European slave names that erased their tribal identity in a single administrative stroke. The scholarly work of Denise I. Bossy documents the Charlestown Indian slave trade as the largest in the colonial Americas, with enslaved Indigenous people sold across British colonies from New England to the Caribbean. (Bossy, Indian Slavery in Southeastern Indian and British Societies, 1670–1730, University of Nebraska Press, 2009 — Tier 2 Scholarly)',

      'The legal mechanism of reclassification was explicit. In 1719, the South Carolina colonial legislature passed a statute that read: "all such slaves as are not entirely Indian shall be accounted as negroe." This single sentence accomplished what no battle could: it legally transformed Indigenous identity into Black identity. A person who was half Yamasee and half African was no longer Yamasee. They were Negro. Their land claims, their tribal affiliations, their sovereign status — all of it was erased by a legislative sentence. The Virginia records are even more specific. In York County, Virginia, a 1691 record lists "Kate Indian" as a "negro slave." Between 1715 and 1717, the same county records show "Robin an Indian" reclassified as "Robin a negro." These are not interpretations. These are the words written by the colonial administrators themselves. (Richard B. Moore, The Name Negro: Its Origin and Evil Use, 1960, Black Classic Press — Tier 2 Scholarly, citing primary Virginia county records)',

      '— II. THE CHAIN OF RENAMING —',

      'The renaming did not happen once. It happened in waves, across generations, through every administrative system that touched the lives of Black Native American people. The full chain, documented in the primary sources, runs as follows:',

      'WAVE ONE — TRIBAL NAMES TO SLAVE NAMES (1700s): When Indigenous people were captured and enslaved, their tribal names were replaced with classical European slave names. The names Venus, Scipio, Caesar, Pompey, and Cato appear repeatedly in colonial slave inventories alongside notations of "Indian" or "mulatto" — the colonial term for mixed Indigenous and African ancestry. These names appear in the same inventories as people described as "negro," making it impossible, from the record alone, to distinguish African from Indigenous ancestry once the tribal name was removed.',

      'WAVE TWO — SLAVE NAMES TO FREEDMEN ENROLLMENT NAMES (1866–1906): After emancipation, the Freedmen\'s Bureau and the Dawes Commission created new enrollment records. Black Native Americans who had lived among the Five Civilized Tribes — as enslaved people, as free members of tribal communities, as people of mixed Black and Indigenous ancestry — were enrolled in a separate category: "Freedmen." The Curtis Act of 1898 formalized this separation. The Dawes Rolls created three categories: "Cherokee by blood," "intermarried whites," and "Freedmen." A person with a Cherokee father and an African mother was enrolled as a Freedman — not as Cherokee by blood — regardless of their actual Indigenous ancestry. Angela Y. Walton-Raji, whose genealogical research is the most systematic documentation of this process, notes that approximately 20,000 people were enrolled as Freedmen between 1898 and 1907. Her research reveals that "even when a Native American father was involved, the \'blood\' was often not recorded, leading to their classification as Freedmen rather than \'by blood\' citizens." (Walton-Raji, Black Indian Genealogy Research, Heritage Books, 1993 — Tier 2 Scholarly)',

      'WAVE THREE — FREEDMEN NAMES TO CENSUS "NEGRO" CLASSIFICATION (1930): The 1930 U.S. Census issued enumerator instructions that effectively completed the erasure. Individuals with any "Negro blood" were to be classified as "Negro" — even if they had significant Native American ancestry, even if they identified as Native American, even if their family had lived among a tribal nation for generations. The National Archives documents this instruction in the 1930 Census enumerator manual. The result was that an entire generation of Black Native Americans was reclassified into a single racial category that denied their Indigenous heritage. (David Hendricks and Amy Patterson, "The 1930 Census in Perspective," National Archives Prologue Magazine, Summer 2002 — Tier 1 Primary Source)',

      '— III. THE GENETIC RECORD —',

      'The genetic evidence confirms what the documentary record suggests. A 2015 study published in the American Journal of Human Genetics analyzed 5,269 self-identified African Americans using high-density SNP genotype data. The study found measurable Native American DNA in the African American population across every region of the United States, with the highest concentrations in the Southeast — precisely the region where the colonial Indian slave trade was most active, where the Yamasee War was fought, where the Five Civilized Tribes held enslaved people, and where the Dawes Rolls were administered. (Bryc, K., Durand, E.Y., Macpherson, J.M., Reich, D., and Mountain, J.L., "The Genetic Ancestry of African Americans, Latinos, and European Americans across the United States," American Journal of Human Genetics, 96(1), 37–53, 2015 — Tier 2 Scholarly)',

      'This genetic evidence does not prove any individual\'s tribal affiliation. It cannot substitute for genealogical documentation or tribal enrollment. But it does confirm that the mixing of African and Indigenous populations in the American South was not a marginal phenomenon. It was widespread. And the documentary record shows that when this mixing was recorded, the administrative systems of the colonial and post-colonial United States consistently erased the Indigenous component and classified the person as Negro.',

      '— IV. RICHARD B. MOORE AND THE POLITICS OF NAMING —',

      'In 1960, the Barbadian-American scholar and activist Richard B. Moore published a study titled "The Name Negro: Its Origin and Evil Use." Moore\'s central argument was that the word "Negro" was not a neutral descriptor. It was a colonial invention — a label created by slave traders and colonial administrators to replace the specific ethnic, tribal, and national identities of the people they were classifying. Moore documented how the words "Negro," "Black," "Colored," and "Indian" functioned as administrative categories rather than self-identifications. The people classified were never consulted about the names used to describe them.',

      'Moore\'s work is particularly significant for Black Native American history because it documents the specific legal mechanisms by which Indigenous identity was reclassified as Black identity. The 1719 South Carolina statute — "all such slaves as are not entirely Indian shall be accounted as negroe" — is precisely the kind of administrative renaming Moore was analyzing. The California State Supreme Court\'s 1854 ruling that "Black person" included all non-Caucasians is another. These were not descriptions. They were legal transformations. They took a person who was Yamasee, or Creek, or Seminole, and made them, in the eyes of the law, Negro. (Moore, Richard B., The Name Negro: Its Origin and Evil Use, 1960, Black Classic Press — Tier 2 Scholarly)',

      '— V. THE FIVE CIVILIZED TRIBES AND THE COMPLEXITY OF BLACK NATIVE SLAVERY —',

      'The history of Black Native American identity cannot be told without confronting a painful complexity: the Five Civilized Tribes — the Cherokee, Chickasaw, Choctaw, Creek, and Seminole — themselves enslaved Black people. This is documented in the primary sources. The Choctaw slaveholder Benjamin Franklin Colbert owned Kiziah Love and at least 24 other enslaved Black individuals. After the forced removal of the Five Civilized Tribes to Indian Territory in the 1830s and 1840s, approximately 7,000 enslaved Black people accompanied them — forming an isolated labor pool in Indian Territory. The tribes adopted racial ideologies similar to those of the white slaveholding South.',

      'But the complexity deepens. Many of the people enslaved by the Five Civilized Tribes had Indigenous ancestry themselves — people who were the descendants of earlier colonial Indian slave trade victims, people of mixed Black and Creek or Black and Cherokee ancestry who had been reclassified as Negro by the colonial administrative systems documented above. The Seminole case is the most documented: the Black Seminoles were a distinct community of people of African and Seminole descent who had lived among the Seminole Nation for generations, spoke Seminole languages, fought in Seminole wars, and were recognized as part of the Seminole community — until the Dawes Commission enrolled them as Freedmen rather than Seminoles by blood. (Krauthamer, Barbara, Black Slaves, Indian Masters: Slavery, Emancipation, and Citizenship in the Native American South, University of North Carolina Press, 2013 — Tier 2 Scholarly)',

      '— VI. THE WALTON-RAJI METHODOLOGY: HOW TO FIND THE ERASED —',

      'Angela Y. Walton-Raji\'s genealogical research represents the most systematic methodology for recovering Black Native American identity from the documentary record. Her approach begins with the Freedmen\'s Bureau records and the Dawes Rolls at the National Archives, cross-referencing them against tribal census records, land allotment records, and the 1832 Parsons and Abbott Census of the Creek Nation. Her personal research began with discovering her great-grandmother Sally\'s Choctaw heritage — a heritage that had been invisible in the family\'s oral history because it had been administratively erased by the Freedmen enrollment process.',

      'Walton-Raji\'s methodology reveals a specific pattern: when a Black Native American family was enrolled in the Dawes Rolls, the enrollment card often listed the mother\'s race as "Negro" and the father\'s race as blank — not because the father was unknown, but because the Dawes commissioners did not record Indigenous paternity for Freedmen enrollees. The "blood" was not recorded. The Indigenous ancestry was administratively erased at the moment of enrollment. Walton-Raji\'s work provides the tools to recover it: by cross-referencing the Freedmen enrollment card with the tribal census rolls, the land allotment records, and the Freedmen\'s Bureau labor contracts, researchers can often reconstruct the Indigenous ancestry that the Dawes Commission did not record. (Walton-Raji, Angela Y., Black Indian Genealogy Research, Heritage Books, 1993 — Tier 2 Scholarly)',

      '— VII. THE CREEK WAR THEORY — TIER 3 COMMUNITY HISTORICAL TRADITION —',

      'Within the Black Native American community, a theory has circulated — most prominently associated with the researcher known as DaGhettoScholar — that the Creek War of 1813–1814 resulted in the large-scale capture and enslavement of Creek people who were subsequently classified as "Negro" in American census records. The theory holds that the Battle of Horseshoe Bend (March 27, 1814), in which Andrew Jackson\'s forces killed approximately 800 Creek warriors and captured hundreds of survivors, resulted in a mass reclassification of Creek prisoners as enslaved Negroes rather than prisoners of war.',

      'This theory is presented here as Tier 3 — Community Historical Tradition — because it has not been confirmed by primary source documentation at the scale the theory claims. The 1832 Parsons and Abbott Census of the Creek Nation, held at the National Archives (Record Group 75, M275), documents slaveholding within Creek households but does not record a mass reclassification of Creek war captives as Negro. The broader historical context — the 1719 South Carolina statute, the Virginia county records, the Dawes Rolls enrollment practices — does confirm that reclassification of Indigenous people as Negro was a documented practice. Whether it occurred at the scale and in the specific manner the Creek War theory claims requires additional primary source documentation to be elevated from Tier 3 to Tier 1 or Tier 2.',

      'The Archive Encyclopedia presents this theory with respect for the community tradition it represents, and with the recognition that the absence of primary source confirmation is not the same as disproof. The documented history of administrative erasure makes it entirely plausible that primary source evidence of such reclassification exists in records that have not yet been systematically examined. The theory deserves serious scholarly investigation. (Parsons and Abbott Census, 1832, National Archives, Record Group 75, M275 — Tier 1 Primary Source; DaGhettoScholar, community historical tradition — Tier 3)',

      '— VIII. THE WASHITAW NATION AND THE MAISON ROUGE GRANT — TIER 3 —',

      'The Washitaw de Dugdahmoundyah is a reclamation movement that claims pre-Columbian Black Indigenous origins in the Mississippi Valley, asserting sovereignty over lands in Louisiana based on the 1795 Maison Rouge Land Grant. The movement\'s claims represent the most developed Tier 3 reclamation narrative in Black Native American history, and they deserve both respect and precision.',

      'The Tier 1 primary source evidence on the Maison Rouge grant is unambiguous. The United States Supreme Court ruled in United States v. Turner (52 U.S. 663, 1850) that the 1797 contract between Baron de Carondelet and the Marquis de Maison Rouge "conveyed no interest in the land to Maison Rouge." The Court held that the contract merely outlined boundaries for an authorized establishment — it did not convey private land ownership. The land passed to the United States with the Louisiana Purchase. This ruling is consistent with United States v. King and Coxe (3 How. 773, 1845), which clarified that Spanish law required explicit language for private property grants — language that was absent from the Maison Rouge contract.',

      'What the primary sources do confirm is this: before the 1803 Louisiana Purchase, New Orleans had a significant free Black community of approximately 5,000 individuals by 1810, some of whom achieved considerable wealth. François Lacroix held over $200,000 in real estate by 1861. These were real people with real histories — free Black communities in Louisiana before American sovereignty, with documented property ownership and community ties. The Washitaw reclamation narrative, whatever its legal standing, draws on a real history of Black presence in the Mississippi Valley that predates American jurisdiction. The Archive Encyclopedia presents the Washitaw claims as Tier 3 — Community Historical Tradition — while honoring the documented history of erasure that makes such reclamation claims historically significant. (United States v. Turner, 52 U.S. 663, 1850 — Tier 1 Primary Source)',

      '— IX. WHAT THE EVIDENCE PROVES —',

      'The documented evidence, taken together, establishes the following with primary source confirmation: First, Indigenous people captured in colonial wars were systematically renamed and sold into slavery, appearing in colonial records under English names that erased their tribal identity. Second, specific colonial laws — including the 1719 South Carolina statute — legally reclassified people of mixed Indigenous and African ancestry as Negro, erasing their Indigenous identity in a single administrative act. Third, the Dawes Commission enrollment process (1898–1907) enrolled Black Native Americans as Freedmen rather than by blood, regardless of their actual Indigenous ancestry, denying them full tribal rights. Fourth, the 1930 Census enumerator instructions completed the erasure by classifying anyone with any "Negro blood" as Negro, regardless of Indigenous ancestry. Fifth, genetic evidence confirms widespread Native American ancestry in the African American population, with the highest concentrations in the Southeast — precisely where these administrative erasures were most active.',

      'What the evidence does not yet prove — and what requires additional primary source documentation — is the specific scale of the Creek War reclassification and the legal validity of the Washitaw land claims. These are presented as Tier 3 community traditions, not established historical fact. The distinction matters. This encyclopedia is built on the principle that documented history is more powerful than undocumented theory. The documented history of Black Native American renaming and erasure is extraordinary enough. It does not need embellishment. It needs to be read.',

      'The people who were renamed are not a mystery. They are in the records. They are in the Dawes Rolls, classified as Freedmen when their fathers were Creek or Cherokee. They are in the Virginia county records, reclassified from Indian to Negro between 1715 and 1717. They are in the 1720s Carolina census, listed under classical European slave names with no tribal affiliation recorded. They are in the genetic data, carrying Native American DNA that their official records do not acknowledge. They were here before the ships arrived. They were renamed. And the renaming is documented.',
    ],
    pullQuote: {
      text: 'In 1719, the South Carolina colonial legislature declared: "all such slaves as are not entirely Indian shall be accounted as negroe." In Virginia, between 1715 and 1717, "Robin an Indian" became "Robin a negro" in the same county records. This was not a gradual cultural shift. It was a legal transformation — accomplished by statute, enforced by census, and sustained across generations.',
      attribution: 'The Archive Encyclopedia, citing Richard B. Moore, The Name Negro: Its Origin and Evil Use (1960), and Virginia County Records (1691–1717)'
    },
    didYouKnow: 'The 1930 U.S. Census enumerator instructions directed that anyone with any "Negro blood" be classified as "Negro" — regardless of Indigenous ancestry, tribal affiliation, or self-identification. This single administrative instruction completed a process that had begun with the 1719 South Carolina statute. The people classified were never consulted. The National Archives holds both documents.',
    keyDocuments: [
      'Bossy, Denise I. Indian Slavery in Southeastern Indian and British Societies, 1670–1730 (2009), University of Nebraska Press — Tier 2 Scholarly',
      'Moore, Richard B. The Name Negro: Its Origin and Evil Use (1960), Black Classic Press — Tier 2 Scholarly',
      'Walton-Raji, Angela Y. Black Indian Genealogy Research (1993), Heritage Books — Tier 2 Scholarly',
      'Bryc, K. et al. "The Genetic Ancestry of African Americans, Latinos, and European Americans across the United States," American Journal of Human Genetics, 96(1), 37–53 (2015) — Tier 2 Scholarly',
      'Parsons and Abbott Census (1832), National Archives, Record Group 75, M275 — Tier 1 Primary Source',
      'Hendricks, David and Patterson, Amy. "The 1930 Census in Perspective," National Archives Prologue Magazine, Summer 2002 — Tier 1 Primary Source',
      'Krauthamer, Barbara. Black Slaves, Indian Masters (2013), University of North Carolina Press — Tier 2 Scholarly',
      'United States v. Turner, 52 U.S. 663 (1850), U.S. Supreme Court — Tier 1 Primary Source',
      'Curtis Act (1898), 30 Stat. 495 — Tier 1 Primary Source',
      'South Carolina Slave Code (1719), Colonial Records of South Carolina — Tier 1 Primary Source',
    ],
  },
};

export function getBlackNativeContent(slug: string): ChapterContent | undefined {
  return BLACK_NATIVE_CONTENT[slug];
}
