export interface Chapter {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  era: string;
  eraColor: string;
  summary: string;
  tier: 1 | 2 | 3;
  keyFact: string;
  primarySource?: string;
  image?: string;
}

export interface Figure {
  name: string;
  years: string;
  heritage: string;
  role: string;
  quote: string;
  image: string;
  connection: string;
}

export const ERAS = [
  { id: 1, name: "Era I: Imperial Origins (1452–1732)", color: "#8b1a1a" },
  { id: 2, name: "Era II: Dispossession & Erasure (1783–1900)", color: "#d4af37" },
  { id: 3, name: "Era III: Economic Extraction (1862–1945)", color: "#2d6a4f" },
  { id: 4, name: "Era IV: Psychological Warfare (1865–1972)", color: "#6b3fa0" },
  { id: 5, name: "Era V: The Modern Resistance (1954–Present)", color: "#1d6fa4" },
];

export const CHAPTERS: Chapter[] = [
  {
    id: 1, slug: "etowah-mounds", title: "The Etowah Mounds",
    subtitle: "Before the Conquest: The Mississippian World",
    era: "Era I", eraColor: "#8b1a1a",
    summary: "Long before European contact, the Etowah site in present-day Georgia was a thriving Mississippian city of 4,000 people — one of the most sophisticated civilizations in pre-Columbian North America.",
    tier: 1,
    keyFact: "The Etowah Mounds in Cartersville, Georgia represent a civilization that predates the 1732 Georgia Charter by over 500 years.",
    primarySource: "Earl H. Morris, The Temple of the Warriors at Chichen Itza (Carnegie Institution, 1931)",
    image: "/manus-storage/scene_etowah_fd5e50db.png"
  },
  {
    id: 2, slug: "georgia-charter", title: "The 1732 Georgia Charter",
    subtitle: "The Legal Fiction of Discovery",
    era: "Era I", eraColor: "#8b1a1a",
    summary: "King George II granted the 1732 Georgia Charter to a corporate body of Trustees, describing inhabited Indigenous lands as 'waste and desolate' — the foundational legal fiction of American dispossession.",
    tier: 1,
    keyFact: "The 1732 Georgia Charter described Creek and Cherokee territories as 'waste and desolate' — erasing thousands of Indigenous inhabitants with a single legal phrase.",
    primarySource: "Georgia Charter (1732), Avalon Project, Yale Law School",
    image: "/manus-storage/scene_georgia_charter_1f896a97.png",
  },
  {
    id: 3, slug: "sovereignty", title: "The Enforcement Gap",
    subtitle: "Worcester v. Georgia and the Betrayal of Sovereignty",
    era: "Era I", eraColor: "#8b1a1a",
    summary: "In 1832, Chief Justice John Marshall ruled that Georgia had no jurisdiction over Cherokee territory. President Andrew Jackson refused to enforce the ruling, establishing the template for state power overriding federal law.",
    tier: 1,
    keyFact: "Andrew Jackson's refusal to enforce Worcester v. Georgia established the precedent that state power could override federal law when the federal government lacked the will to enforce it.",
    primarySource: "Worcester v. Georgia, 31 U.S. 515 (1832)",
    image: "/manus-storage/scene_sovereignty_b501ba4d.png",
  },
  {
    id: 4, slug: "haitian-revolution", title: "The Haitian Revolution",
    subtitle: "The International Context of American Slavery",
    era: "Era I", eraColor: "#8b1a1a",
    summary: "The 1791 Haitian Revolution terrified American slaveholders and directly caused the tightening of slave codes across the South. Thomas Jefferson's embargo of Haiti proved the U.S. would sacrifice trade to protect slavery.",
    tier: 1,
    keyFact: "The Haitian Revolution caused the U.S. to enact draconian restrictions on free Black people in New Orleans and tighten slave codes across the South.",
    primarySource: "Thomas Jefferson, Embargo Act correspondence (1806), National Archives",
    image: "/manus-storage/scene_haitian_revolution_f378b7ef.png",
  },
  {
    id: 5, slug: "identity-erasure", title: "The Paper Genocide",
    subtitle: "The 1930 Census and the Erasure of Black Indigenous Identity",
    era: "Era II", eraColor: "#d4af37",
    summary: "The 1930 U.S. Census enumerator instructions mandated that anyone with mixed Black and Indigenous ancestry be classified as 'Negro' — erasing hundreds of thousands of people from the legal record in a single enumeration cycle.",
    tier: 1,
    keyFact: "The 1930 Census instruction: 'A person of mixed Indian and Negro blood should be returned a Negro, unless the Indian blood predominates and the status as an Indian is generally accepted in the community.'",
    primarySource: "U.S. Census Bureau, 1930 Enumerator Instructions, National Archives",
    image: "/manus-storage/scene_paper_genocide_36d39695.png",
  },
  {
    id: 6, slug: "resistance", title: "Resistance and Survival",
    subtitle: "Armed and Intellectual Struggle",
    era: "Era II", eraColor: "#d4af37",
    summary: "History is equally the story of resistance. From the Cherokee Phoenix newspaper to the Black Seminole warriors, from Sequoyah's syllabary to Principal Chief John Ross's legal battles, the dispossessed never stopped fighting.",
    tier: 1,
    keyFact: "In 1828, the Cherokee Nation launched the Cherokee Phoenix — the first Native American newspaper — as an act of intellectual sovereignty.",
    primarySource: "Cherokee Phoenix, Vol. 1, No. 1 (February 21, 1828)",
  },
  {
    id: 7, slug: "reclamation", title: "Alternative Narratives",
    subtitle: "Reclamation, Identity, and Community Historical Traditions",
    era: "Era II", eraColor: "#d4af37",
    summary: "Alongside the official historical record, communities have preserved alternative narratives of their origins and sovereignty. These Community Historical Traditions serve profound psychological and cultural functions.",
    tier: 3,
    keyFact: "The Washitaw Nation's claims to pre-Columbian sovereignty are grounded in the Maison Rouge land grant of 1795 — a Tier 1 primary source wrapped in a Tier 3 interpretive framework.",
    primarySource: "Verdiacee Washitaw-Turner Goston El-Bey, Return of the Ancient Ones (1993)",
    image: "/manus-storage/scene_reclamation_6e6eb4af.png",
  },
  {
    id: 8, slug: "reconstruction", title: "The Reconstruction Betrayal",
    subtitle: "The Promise Made and Broken (1865–1877)",
    era: "Era II", eraColor: "#d4af37",
    summary: "The end of the Civil War offered a brief window to restructure American power. President Andrew Johnson systematically dismantled Reconstruction, revoking 40 Acres and a Mule and enabling the Black Codes.",
    tier: 1,
    keyFact: "In 1898, a mob of 2,000 white supremacists overthrew the legitimately elected biracial government of Wilmington, NC — the only successful coup d'état in U.S. history.",
    primarySource: "David Zucchino, Wilmington's Lie (Pulitzer Prize, 2021)",
    image: "/manus-storage/scene_wilmington_massacre_86fe794e.png",
  },
  {
    id: 9, slug: "dawes-act", title: "The 1887 Dawes Act",
    subtitle: "The Theft of 90 Million Acres",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The General Allotment Act of 1887 destroyed communal Indigenous land ownership, transferring approximately 90 million acres from Native nations to white settlers, railroads, and corporations.",
    tier: 1,
    keyFact: "Between 1887 and 1934, Native Americans lost approximately 90 million acres — nearly two-thirds of all the territory they held in 1887.",
    primarySource: "Kappler, Indian Affairs: Laws and Treaties, Vol. I (Oklahoma State University)",
    image: "/manus-storage/scene_dawes_act_34da5aae.png",
  },
  {
    id: 10, slug: "boarding-schools", title: "Kill the Indian, Save the Man",
    subtitle: "The Indian Boarding School System",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "Beginning in 1879, the U.S. government funded hundreds of Indian boarding schools designed to forcibly assimilate Native American children. Children were forbidden to speak their languages, stripped of their names, and subjected to systematic abuse.",
    tier: 1,
    keyFact: "Recent federal reports identified marked and unmarked burial sites at 65 of the more than 400 Indian boarding schools, documenting the deaths of nearly 1,000 Native children.",
    primarySource: "U.S. Department of the Interior, Federal Indian Boarding School Initiative (2022)",
    image: "/manus-storage/scene_boarding_schools_5cee82d4.png",
  },
  {
    id: 11, slug: "sleeping-giant", title: "The Sleeping Giant",
    subtitle: "The Creation of a Permanent Consumer Class",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The dispossession of land and erasure of identity were only the first steps. The ultimate goal was the creation of a permanent, dependent consumer class — a demographic with immense economic energy conditioned to function as wards of the state.",
    tier: 2,
    keyFact: "African Americans possess $1.6–1.9 trillion in annual spending power yet hold less than 5% of the nation's wealth — the mathematical result of centuries of systematic extraction.",
    primarySource: "Dr. Claud Anderson, PowerNomics (2001); McKinsey & Company, The Economic Impact of Closing the Racial Wealth Gap (2019)",
    image: "/manus-storage/scene_sleeping_giant_33743358.png",
  },
  {
    id: 12, slug: "wealth-extraction", title: "Wealth Extraction",
    subtitle: "The Tulsa Race Massacre and the Bulldozing of Black Wealth",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "When Black communities successfully built autonomous wealth, they were met with state-sanctioned violence. The 1921 Tulsa Race Massacre destroyed 35 square blocks of the Greenwood District. Atlanta's highway system bulldozed Sweet Auburn Avenue.",
    tier: 1,
    keyFact: "On May 31–June 1, 1921, a white mob destroyed 35 square blocks of the Greenwood District. No white person was ever charged. Insurance companies denied all claims.",
    primarySource: "Oklahoma Commission to Study the Tulsa Race Riot of 1921, Final Report (2001)",
    image: "/manus-storage/scene_tulsa_9e4c2b56.png"
  },
  {
    id: 13, slug: "builders", title: "The Builders of America",
    subtitle: "Black Genius and the Infrastructure of a Nation",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "Despite immense systemic barriers, Black inventors secured thousands of patents that revolutionized global industry. Elijah McCoy, Lewis Latimer, Granville T. Woods, and Jan Ernst Matzeliger built the modern world while being denied its benefits.",
    tier: 1,
    keyFact: "Granville T. Woods invented the multiplex telegraph system used on railroads — at the exact same time Black men were being leased as convicts to build those same railroad tracks.",
    primarySource: "U.S. Patent Office Records, National Archives",
    image: "/manus-storage/scene_builders_america_419c6cdc.png",
  },
  {
    id: 14, slug: "intellectual-resistance", title: "The Intellectual Resistance",
    subtitle: "Black Authors, Scholars, and the Power of Literacy",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The intellectual architecture of liberation was built upon essential texts. From Frederick Douglass's Narrative to Carter G. Woodson's Mis-Education of the Negro, Black scholars systematically dismantled the dominant historical narrative.",
    tier: 2,
    keyFact: "Carter G. Woodson's The Mis-Education of the Negro (1933) argued that the American educational system was deliberately designed to prevent Black Americans from understanding their own history.",
    primarySource: "Carter G. Woodson, The Mis-Education of the Negro (1933); J.A. Rogers, Nature Knows No Color-Line (1952)",
    image: "/manus-storage/portrait_douglass_8d952b5e.png"
  },
  {
    id: 15, slug: "sound-of-resistance", title: "The Sound of Resistance",
    subtitle: "From Minstrelsy to Motown: The Chronological History of Black Music",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "Black music is the story of the entire manuscript compressed into sound: erasure, theft, resistance, genius, and the ultimate proof that no system of oppression can extinguish the human spirit.",
    tier: 1,
    keyFact: "Berry Gordy's Motown Records (1959) executed vertical integration — Black-owned, Black-produced, Black-distributed — generating 'The Sound of Young America' that forced white audiences to consume Black art on Black terms.",
    primarySource: "Thompson & Olsen, The Science and Psychology of Music (Greenwood, 2020)",
    image: "/manus-storage/scene_motown_e672d208.png"
  },
  {
    id: 16, slug: "great-migration", title: "The Great Migration",
    subtitle: "Six Million Votes With Their Feet (1910–1970)",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "Between 1910 and 1970, approximately six million Black Americans relocated from the rural South to the urban North and West — the largest internal migration in American history, and one of the most profound acts of collective resistance.",
    tier: 1,
    keyFact: "From Georgia alone, 74,000 Black residents departed between 1910 and 1920. Chicago's Black population grew 148% in a decade. Detroit's grew 611%.",
    primarySource: "Isabel Wilkerson, The Warmth of Other Suns (2010)",
    image: "/manus-storage/scene_great_migration_e8da5b75.png",
  },
  {
    id: 17, slug: "psychological-warfare", title: "The Architecture of Psychological Warfare",
    subtitle: "Terror, Science, and the Control of the Mind (1865–1972)",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "The theft of land and labor required a third mechanism: the psychological subjugation of the population. This was achieved through Social Darwinism, public lynching as spectacle, the Tuskegee Study, and the deliberate weaponization of national holidays.",
    tier: 1,
    keyFact: "The Dyer Anti-Lynching Bill passed the House in 1921 but was killed by a Senate filibuster. The U.S. did not pass a federal anti-lynching law until the Emmett Till Antilynching Act of 2022 — 101 years later.",
    primarySource: "Equal Justice Initiative, Lynching in America (2017); FBI Vault, COINTELPRO Black Extremist Part 01 (1967)",
    image: "/manus-storage/scene_psychological_warfare_055e1d78.png",
  },
  {
    id: 18, slug: "entertainment-industry", title: "The Industrialization of Dehumanization",
    subtitle: "From Minstrelsy to Hollywood to the Modern Entertainment Complex",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "Physical terror was accompanied by narrative control. The minstrel show, the coon song craze, Birth of a Nation, and the Hollywood Production Code systematically dehumanized Black people for mass audiences.",
    tier: 1,
    keyFact: "The CIA's Congress for Cultural Freedom (1950–1967) and Operation Mockingbird proved the government's willingness to use cultural production as an instrument of psychological warfare.",
    primarySource: "Donald Bogle, Toms, Coons, Mulattoes, Mammies, and Bucks (1973); Church Committee Report (1976)",
    image: "/manus-storage/scene_entertainment_industry_decebfa1.png",
  },
  {
    id: 19, slug: "epigenetics", title: "The Biology of History",
    subtitle: "Epigenetics, Intergenerational Trauma, and the DNA of Oppression",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "Modern science has proven that trauma manifests as measurable biological changes inherited across generations. The history is not in the past — it is in the DNA.",
    tier: 1,
    keyFact: "A 2017 peer-reviewed study (Janusek et al., Brain, Behavior, and Immunity) found that childhood adversity in young African American men directly alters the methylation of the IL6 gene, causing chronic inflammation.",
    primarySource: "Janusek et al., Brain, Behavior, and Immunity (2017); Dr. Rachel Yehuda, Biological Psychiatry (2015)",
    image: "/manus-storage/scene_epigenetics_f7558ed1.png",
  },
  {
    id: 20, slug: "women-of-resistance", title: "Women of Resistance",
    subtitle: "Harriet Tubman, Zitkala-Sa, Ida B. Wells, and the Architects of Liberation",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "The narrative of American resistance is often incomplete, overlooking the profound leadership of Black and Indigenous women who challenged systemic oppression and laid the groundwork for future movements.",
    tier: 1,
    keyFact: "Harriet Tubman was the first woman in U.S. history to lead a military operation — the 1863 Combahee River Raid, which liberated over 750 enslaved people.",
    primarySource: "Kate Clifford Larson, Bound for the Promised Land: Harriet Tubman (2004)",
    image: "/manus-storage/portrait_wells_e6de28c9.png"
  },
  {
    id: 21, slug: "institutions", title: "Institutions of Preservation",
    subtitle: "Museums, Archives, and the Architecture of Memory",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "As the state deployed legal and physical mechanisms of erasure, Black and Indigenous communities built institutions to preserve their history. From the NAACP (1909) to the NMAAHC (2016), these institutions are active defense mechanisms against ongoing erasure.",
    tier: 1,
    keyFact: "The National Park Service's 2020 report 'Black Lives and Whitened Stories' formally acknowledged that its own historical sites had systematically erased Black history — proving that autonomous institutions of preservation are a historical necessity.",
    primarySource: "Whisnant & Whisnant, Black Lives and Whitened Stories (NPS, 2020)",
    image: "/manus-storage/scene_institutions_b1af24f2.png",
  },
  {
    id: 22, slug: "accountability", title: "Accountability and Tangible Action",
    subtitle: "Legal Frameworks for Restorative Justice",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "The historical record is clear: the crimes documented in this encyclopedia were state-sanctioned policies. Accountability is legally possible; it only lacks political will.",
    tier: 1,
    keyFact: "University of Connecticut economist Thomas Craemer calculated that the value of enslaved labor, compounded at 3% interest, equals approximately $14 trillion.",
    primarySource: "Thomas Craemer, Estimating Slavery Reparations (2015); Germany Holocaust Reparations, Federal Ministry of Finance",
    image: "/manus-storage/scene_accountability_df6df22b.png",
  },
  {
    id: 23, slug: "chinese-exclusion", title: "The Chinese Exclusion Act",
    subtitle: "The First Federal Law to Bar a Racial Group from Immigration (1882)",
    era: "Era II", eraColor: "#d4af37",
    summary: "The Chinese Exclusion Act of 1882 was the first federal law to explicitly bar a racial group from immigration. It established the legal template for racially discriminatory immigration policy that would culminate in the 1924 National Origins Act and shape American immigration law for a century.",
    tier: 1,
    keyFact: "The Chinese Exclusion Act of 1882 was not repealed until 1943 — 61 years after it was enacted — and only because China was a U.S. ally in World War II.",
    primarySource: "Chinese Exclusion Act (1882), 22 Stat. 58, National Archives",
    image: "/manus-storage/scene_chinese_exclusion_952ccfee.png",
  },
  {
    id: 24, slug: "buffalo-soldiers", title: "The Buffalo Soldiers",
    subtitle: "Black Warriors for a Country That Returned Them to Jim Crow (1866–1898)",
    era: "Era II", eraColor: "#d4af37",
    summary: "The Buffalo Soldiers were Black military regiments who fought in the Indian Wars and the Spanish-American War. They were celebrated as heroes in Cuba in 1898 — and returned to Jim Crow America, where they were denied the rights they had fought to defend.",
    tier: 1,
    keyFact: "The Buffalo Soldiers received 23 Congressional Medals of Honor — the highest military honor in the United States — yet returned home to segregation, lynching, and the denial of basic civil rights.",
    primarySource: "Buffalo Soldiers National Museum; Congressional Medal of Honor Society records",
    image: "/manus-storage/scene_buffalo_soldiers_505c3800.png",
  },
  {
    id: 25, slug: "bracero-program", title: "The Bracero Program",
    subtitle: "The Exploitation of Mexican Agricultural Labor (1942–1964)",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The Bracero Program (1942–1964) brought approximately 4.6 million Mexican agricultural workers to the United States under conditions nearly identical to convict leasing. Workers were unable to leave their employers, wages were withheld, and a 10% 'savings fund' was never paid.",
    tier: 1,
    keyFact: "The U.S. government withheld 10% of Bracero wages in a 'savings fund' that was supposed to be returned when workers went home. Most workers never received this money. Advocates estimate the stolen wages total over $500 million.",
    primarySource: "Bracero History Archive, Library of Congress; Gamboa, Erasmo. Mexican Labor and World War II (1990)",
    image: "/manus-storage/scene_bracero_program_d9495b50.png",
  },
  {
    id: 26, slug: "gullah-geechee", title: "The Gullah Geechee",
    subtitle: "Enduring Culture of the Sea Islands",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The Gullah Geechee people are direct descendants of enslaved Africans who maintained the most intact African cultural traditions in North America, living on the Sea Islands of Georgia and South Carolina. Their survival is a testament to the resilience of African culture against the most brutal conditions of American slavery.",
    tier: 1,
    keyFact: "The Gullah Geechee Corridor National Heritage Area was federally designated in 2006, spanning from North Carolina to Florida — recognizing the most intact African cultural tradition in North America.",
    primarySource: "Gullah Geechee Cultural Heritage Corridor National Heritage Area (NPS, 2006)",
    image: "/manus-storage/scene_gullah_geechee_f378b7ef.png",
  },
  {
    id: 24, slug: "five-tribes-slavery", title: "The Complexity of Alliance",
    subtitle: "The Five Civilized Tribes and the Enslavement of Black People",
    era: "Era II", eraColor: "#d4af37",
    summary: "The history of the Five Civilized Tribes is deeply intertwined with the institution of chattel slavery. By 1860, the Five Tribes collectively held over 7,300 enslaved Black people — a history that complicates the Black-Indigenous alliance narrative in ways that intellectual honesty demands we address.",
    tier: 1,
    keyFact: "By 1860, the Five Civilized Tribes collectively held over 7,300 enslaved Black people. The Chickasaw Nation had the highest proportion — 18% of their total population — comparable to white slaveholders in neighboring Tennessee.",
    primarySource: "Doran, Michael F. 'Negro Slaves of the Five Civilized Tribes.' Annals of the Association of American Geographers (1978)",
    image: "/manus-storage/scene_five_tribes_slavery_7a38ec83.png",
  },
  {
    id: 25, slug: "black-cowboys", title: "The Black Cowboys",
    subtitle: "The Builders of the American West, Erased from History",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "Approximately one in four cowboys in the American West during the late 19th century were Black — a history almost entirely erased from popular culture through dime novels, Wild West shows, and Hollywood westerns. This erasure is a direct example of the industrialization of dehumanization documented in this encyclopedia.",
    tier: 1,
    keyFact: "Approximately 1 in 4 cowboys in the American West were Black. Bill Pickett, a Black cowboy, invented the technique of bulldogging (steer wrestling) — a rodeo staple still practiced today.",
    primarySource: "Durham, Philip and Jones, Everett L. The Negro Cowboys (1965); Nat Love, The Life and Adventures of Nat Love (1907)",
  },
  {
    id: 29, slug: "black-vietnam-veterans", title: "Black Vietnam Veterans",
    subtitle: "Project 100,000, PTSD, and the Urban Aftermath",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "40.6% of Project 100,000 participants were Black — more than three times their military representation. These men experienced double the combat casualty rate of other recruits. They returned home to documented VA benefit denials, PTSD without support, and communities being targeted by the War on Drugs.",
    tier: 1,
    keyFact: "Project 100,000 drafted 354,000 men who had previously been deemed unfit for service. 40.6% were Black. They experienced a 20% combat casualty rate — double the rate of other recruits.",
    primarySource: "ERIC Document ED031634, Project One Hundred Thousand; American War Library, Vietnam War Casualties by Race",
    image: "/manus-storage/scene_vietnam_veterans_7979260f.png",
  },
  {
    id: 30, slug: "crack-epidemic-iran-contra", title: "The Crack Epidemic",
    subtitle: "The Kerry Committee, the CIA Inspector General, and the Evidence Record",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "The Kerry Committee Report (1989) and the CIA Inspector General's Report (1998) are Tier 1 primary sources that document CIA awareness of Contra drug trafficking and deliberate inaction. The crack epidemic devastated Black communities. The distinction between documented neglect and unproven deliberate introduction is maintained throughout this chapter.",
    tier: 1,
    keyFact: "The Kerry Committee Report (1989) concluded that 'foreign policy considerations interfered with the U.S.'s ability to fight the war on drugs' and found 'considerable evidence' that Contra supporters were involved in drug trafficking.",
    primarySource: "Kerry Committee Report (1989), U.S. Senate; CIA Inspector General's Report, Volume II: The Contra Story (1998)",
    image: "/manus-storage/scene_crack_epidemic_21efacb0.png",
  },
  {
    id: 31, slug: "iron-pipeline-gun-violence", title: "The Iron Pipeline",
    subtitle: "ATF Gun Tracing Data, Documented Trafficking Networks, and Urban Violence",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "90% of crime guns recovered in New York City were purchased in other states. Georgia, Virginia, and the Carolinas are documented primary source states. The Firearm Owners Protection Act of 1986 weakened ATF enforcement. Operation Fast and Furious is a documented case of government negligence in gun trafficking.",
    tier: 1,
    keyFact: "57% of all crime guns traced by the ATF were sold by just 1.2% of licensed dealers — but the 1986 Firearm Owners Protection Act limited ATF to one unannounced inspection per year per dealer.",
    primarySource: "ATF Crime Gun Trace Reports (annual); House Committee on Oversight, Fast and Furious Final Report (2012)",
    image: "/manus-storage/scene_iron_pipeline_7f7bf656.png",
  },
  {
    id: 32, slug: "kerner-commission", title: "The Kerner Commission Report",
    subtitle: "The Government's Own Verdict on Systemic Racism (1968)",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "In 1968, the federal government's own National Advisory Commission on Civil Disorders concluded that America was 'moving toward two societies, one Black, one white — separate and unequal.' The report identified white racism as the primary cause of urban unrest. President Johnson buried it. Its findings have never been fully implemented.",
    tier: 1,
    keyFact: "The Kerner Commission concluded in 1968: 'Our nation is moving toward two societies, one Black, one white — separate and unequal.' The report explicitly identified 'white racism' as the primary cause. President Johnson refused to meet with the commission and buried the report.",
    primarySource: "National Advisory Commission on Civil Disorders, Report of the National Advisory Commission on Civil Disorders (1968) — Kerner Commission Report, National Archives",
    image: "/manus-storage/scene_kerner_commission_9fcefbff.png",
  },
  {
    id: 33, slug: "aids-epidemic-federal-delay", title: "The AIDS Epidemic and the Federal Delay",
    subtitle: "Six Years of Documented Government Inaction (1981–1987)",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "The Reagan administration's documented six-year delay in responding to the AIDS epidemic allowed a preventable health crisis to devastate Black and gay communities. The first reported cases were in 1981. Reagan did not publicly mention AIDS until 1987. By then, 41,000 Americans had died.",
    tier: 1,
    keyFact: "Reagan's press secretary Larry Speakes laughed when asked about AIDS in 1982. Reagan did not publicly mention AIDS until May 31, 1987 — six years after the first cases were reported. By then, 41,000 Americans had died.",
    primarySource: "Reagan Presidential Library records; CDC Morbidity and Mortality Weekly Report (1981); Randy Shilts, And the Band Played On (1987)",
    image: "/manus-storage/scene_aids_epidemic_eda8556d.png",
  },
  {
    id: 34, slug: "subprime-mortgage-crisis", title: "The 2008 Subprime Mortgage Crisis",
    subtitle: "Documented Racial Targeting and the Largest Fair Lending Settlement in DOJ History",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "Wells Fargo and other major banks were documented by the U.S. Department of Justice to have specifically targeted Black homeowners for predatory subprime mortgages. Wells Fargo paid $175 million in the largest fair lending settlement in DOJ history. The 2008 crisis wiped out 53% of Black household wealth.",
    tier: 1,
    keyFact: "Wells Fargo paid $175 million in 2012 in the largest fair lending settlement in DOJ history. The DOJ documented that Wells Fargo loan officers referred to Black borrowers as 'mud people' and subprime loans as 'ghetto loans.'",
    primarySource: "U.S. Department of Justice, United States v. Wells Fargo Bank, N.A. (2012); Federal Reserve, Survey of Consumer Finances (2010)",
    image: "/manus-storage/scene_subprime_crisis_0d53149f.png",
  },
  {
    id: 35, slug: "prison-industrial-complex", title: "The Economics of Incarceration",
    subtitle: "Private Prisons, Financial Incentives, and the Modern Continuation of Convict Leasing",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "CoreCivic and GEO Group generated $4.38 billion in revenue in 2024. Their own SEC filings document that their profitability depends on high incarceration rates. Black Americans are incarcerated at 5 times the rate of white Americans. This is not coincidence — it is the documented continuation of the 13th Amendment loophole.",
    tier: 1,
    keyFact: "CoreCivic's 2024 SEC filing explicitly lists 'leniency in conviction or parole standards' as a financial risk to their business — proving in their own words that their profitability depends on high incarceration rates.",
    primarySource: "CoreCivic Form 10-K (2024), SEC EDGAR CIK 1070985; Bureau of Justice Statistics, Prisoners in 2023 (NCJ 310197)",
    image: "/manus-storage/scene_prison_industrial_1280a940.png",
  },
  {
    id: 30, slug: "school-to-prison-pipeline", title: "The School-to-Prison Pipeline",
    subtitle: "Documented Disparities, Zero Tolerance, and the Fatherless Epidemic",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "Black boys are nearly twice as likely as white boys to receive out-of-school suspensions. A single suspension almost triples the likelihood of later juvenile justice involvement. The 'man-in-the-house' rules in public housing structurally excluded Black fathers from family units. These are documented government statistics, not claims.",
    tier: 1,
    keyFact: "According to the U.S. Department of Education Civil Rights Data Collection, Black boys constitute 8% of K-12 enrollment but account for 18% of out-of-school suspensions and 18% of expulsions.",
    primarySource: "U.S. Department of Education, 2020-21 Civil Rights Data Collection; King v. Smith, 392 U.S. 309 (1968)",
    image: "/manus-storage/scene_school_prison_2607bf6d.png",
  },
  {
    id: 31, slug: "redlining-housing-discrimination", title: "Redlining and the Housing Wealth Gap",
    subtitle: "HOLC Maps, Environmental Racism, and the Documented Wealth Denial",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "The HOLC's own 1935 underwriting manuals explicitly listed 'infiltration of Negro occupancy' as a negative factor. 74% of neighborhoods graded 'hazardous' in the 1930s remain low-to-moderate income today. Homes in formerly redlined neighborhoods are valued 23% lower than comparable homes in non-redlined areas.",
    tier: 1,
    keyFact: "The Urban Institute estimates that the homeownership gap between Black and white Americans — currently 29 percentage points — is larger today than it was in 1968 when the Fair Housing Act was passed.",
    primarySource: "HOLC Residential Security Maps (1935-1940), National Archives; National Community Reinvestment Coalition Study (2020), PLOS ONE",
  },
  {
    id: 32, slug: "media-propaganda-behavioral-outcomes", title: "Media, Stereotypes, and Documented Behavioral Outcomes",
    subtitle: "The Ehrlichman Admission, Stereotype Threat, and the Economics of Cultural Production",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "John Ehrlichman admitted in 2016 that the War on Drugs was designed to target Black communities. Claude Steele's stereotype threat research — replicated in 300+ peer-reviewed studies — proves that media stereotypes have a measurable negative impact on academic performance. Three major labels control 68% of the global music market.",
    tier: 1,
    keyFact: "John Ehrlichman, Nixon's domestic policy chief, admitted in 2016: 'Did we know we were lying about the drugs? Of course we did.' This is a direct, first-person admission of racial intent in the War on Drugs.",
    primarySource: "Baum, Dan. 'Legalize It All.' Harper's Magazine (April 2016); Steele & Aronson, Journal of Personality and Social Psychology (1995)",
    image: "/manus-storage/scene_media_propaganda_8d641aba.png",
  },
  {
    id: 33, slug: "dyer-antilynching-bill", title: "The Dyer Anti-Lynching Bill",
    subtitle: "The Federal Government's Choice Not to Act (1921)",
    era: "Era III", eraColor: "#2d6a4f",
    summary: "In 1921, Congressman Leonidas Dyer introduced the first federal anti-lynching bill. It passed the House of Representatives but was killed by a Southern Democratic filibuster in the Senate. The United States did not pass a federal anti-lynching law until 2022 — 101 years later. This is the most direct proof that the federal government had the legal mechanism to stop racial terror and chose not to use it.",
    tier: 1,
    keyFact: "The Dyer Anti-Lynching Bill passed the House in 1922 with 230 votes to 119. It was killed by a Senate filibuster. The U.S. did not pass a federal anti-lynching law until the Emmett Till Antilynching Act of 2022 — 101 years later.",
    primarySource: "H.R. 13 (67th Congress, 1921); Congressional Record, Senate filibuster proceedings (1922); Emmett Till Antilynching Act, Pub. L. 117-107 (2022)",
    image: "/manus-storage/scene_dyer_bill_ae1bd76d.png",
  },
  {
    id: 34, slug: "moynihan-report", title: "The Moynihan Report",
    subtitle: "The Government's Diagnosis That Blamed the Victim (1965)",
    era: "Era IV", eraColor: "#6b3fa0",
    summary: "In 1965, Assistant Secretary of Labor Daniel Patrick Moynihan published 'The Negro Family: The Case for National Action.' The report documented the rising rate of Black single-parent households but attributed it to cultural pathology rather than to the documented policies — redlining, man-in-the-house rules, mass incarceration — that caused it. It shaped welfare policy for decades.",
    tier: 1,
    keyFact: "The Moynihan Report (1965) documented that 23.6% of Black births were to unmarried mothers. It failed to connect this to the documented policies that structurally excluded Black men from families — the man-in-the-house rules struck down by King v. Smith (1968) three years later.",
    primarySource: "Moynihan, Daniel Patrick. 'The Negro Family: The Case for National Action.' U.S. Department of Labor (1965) — National Archives",
    image: "/manus-storage/scene_moynihan_report_0e889c9f.png",
  },
  {
    id: 35, slug: "george-floyd-justice-act", title: "The George Floyd Justice in Policing Act",
    subtitle: "The Modern Parallel to the Dyer Bill — Passed the House, Died in the Senate (2021)",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "In 2021, the George Floyd Justice in Policing Act passed the House of Representatives with 220 votes. It died in the Senate. The bill would have banned chokeholds, ended qualified immunity for police officers, and created a national registry of police misconduct. Its failure is the modern parallel to the 1921 Dyer Anti-Lynching Bill — proving that the enforcement gap documented throughout this encyclopedia persists to the present day.",
    tier: 1,
    keyFact: "The George Floyd Justice in Policing Act passed the House in 2021 but died in the Senate — the same pattern as the Dyer Anti-Lynching Bill of 1921. The enforcement gap is not history. It is the present.",
    primarySource: "H.R. 1280 (117th Congress, 2021); Congressional Record; Senate vote records",
    image: "/manus-storage/scene_george_floyd_act_efd5f198.png",
  },
  {
    id: 36, slug: "living-legacy", title: "The Living Legacy",
    subtitle: "McGirt v. Oklahoma, Land Back, and the Ongoing Struggle",
    era: "Era V", eraColor: "#1d6fa4",
    summary: "The history documented in this encyclopedia is not over. The legal battles, the identity reclamation movements, and the struggle for economic justice are ongoing.",
    tier: 1,
    keyFact: "In 2020, the Supreme Court ruled in McGirt v. Oklahoma that the Muscogee (Creek) Nation's reservation was never formally disestablished — recognizing that nearly half of Oklahoma remains 'Indian Country.'",
    primarySource: "McGirt v. Oklahoma, 591 U.S. ___ (2020); Justice Neil Gorsuch, majority opinion",
  },
];

export const FIGURES: Figure[] = [
  {
    name: "Sequoyah",
    years: "c.1770–1843",
    heritage: "Cherokee Nation",
    role: "Inventor of the Cherokee Syllabary",
    quote: "I will try. If I succeed, I will be a great man.",
    image: "/manus-storage/portrait_sequoyah_068e5e05.png",
    connection: "Created the Cherokee syllabary in 1821, making the Cherokee Phoenix newspaper possible — an act of intellectual sovereignty that proved literacy is the prerequisite for liberation."
  },
  {
    name: "Chief Junaluska",
    years: "c.1775–1858",
    heritage: "Cherokee Nation",
    role: "Warrior and Resistance Leader",
    quote: "If I had known Jackson would drive us from our homes, I would have killed him that day at Horseshoe Bend.",
    image: "/manus-storage/portrait_junaluska_92f279a2.png",
    connection: "Saved Andrew Jackson's life at the Battle of Horseshoe Bend, only to be betrayed by him — the ultimate symbol of the enforcement gap."
  },
  {
    name: "John Horse",
    years: "c.1812–1882",
    heritage: "Black Seminole (African-Seminole)",
    role: "Military Leader and Freedom Fighter",
    quote: "We will fight until we die or are free.",
    image: "/manus-storage/portrait_john_horse_d4725fa7.png",
    connection: "Led Black Seminole resistance against the U.S. Army, proving that Black and Indigenous communities formed powerful alliances against colonial power."
  },
  {
    name: "Principal Chief John Ross",
    years: "1790–1866",
    heritage: "Cherokee Nation",
    role: "Principal Chief of the Cherokee Nation",
    quote: "The perpetrator of a wrong never forgives his victim.",
    image: "/manus-storage/portrait_john_ross_b051df54.png",
    connection: "Led the Cherokee Nation's legal and political resistance against removal, using the U.S. legal system to challenge Georgia's illegal seizure of Cherokee territory."
  },
  {
    name: "Frederick Douglass",
    years: "1818–1895",
    heritage: "African American",
    role: "Abolitionist, Orator, and Statesman",
    quote: "What, to the American slave, is your 4th of July? I answer: a day that reveals to him, more than all other days in the year, the gross injustice and cruelty to which he is the constant victim.",
    image: "/manus-storage/portrait_douglass_8d952b5e.png",
    connection: "Proved that literacy is the prerequisite for liberation. His 1852 address exposed the hypocrisy of national celebration as a tool of psychological warfare."
  },
  {
    name: "Ida B. Wells",
    years: "1862–1931",
    heritage: "African American",
    role: "Journalist and Anti-Lynching Crusader",
    quote: "The way to right wrongs is to turn the light of truth upon them.",
    image: "/manus-storage/portrait_wells_e6de28c9.png",
    connection: "Documented how lynching was used as an economic weapon to eliminate Black business competition — connecting racial terror to the economic extraction model."
  },
  {
    name: "Alonzo Herndon",
    years: "1858–1927",
    heritage: "African American (Born Enslaved)",
    role: "Entrepreneur and Founder of Atlanta Life Insurance",
    quote: "Success is not given; it is earned through relentless work and vision.",
    image: "/manus-storage/portrait_herndon_99584b58.png",
    connection: "Born enslaved, built one of the largest Black-owned businesses in the nation — anchoring Atlanta's Sweet Auburn 'Black Mecca.'"
  },
  {
    name: "Berry Gordy Jr.",
    years: "1929–",
    heritage: "African American",
    role: "Founder of Motown Records",
    quote: "I wanted to make music that would cross over to all people.",
    image: "/manus-storage/portrait_gordy_8e2da39e.png",
    connection: "Executed vertical integration decades before the term existed — proving that when Black creators own the means of production, the economic results are staggering."
  },
];

export const TIMELINE_EVENTS = [
  { year: 1452, event: "Papal Bull Dum Diversas authorizes Portuguese enslavement of non-Christians", era: 1 },
  { year: 1493, event: "Columbus's second voyage establishes the Doctrine of Discovery", era: 1 },
  { year: 1619, event: "First enslaved Africans arrive in Virginia", era: 1 },
  { year: 1732, event: "Georgia Charter describes Indigenous lands as 'waste and desolate'", era: 1 },
  { year: 1776, event: "Declaration of Independence — freedom declared, slavery maintained", era: 1 },
  { year: 1791, event: "Haitian Revolution begins — terrifies American slaveholders", era: 1 },
  { year: 1803, event: "Louisiana Purchase transfers 828,000 sq miles of Indigenous territory", era: 1 },
  { year: 1821, event: "Sequoyah completes the Cherokee syllabary", era: 2 },
  { year: 1828, event: "Cherokee Phoenix newspaper launched", era: 2 },
  { year: 1830, event: "Indian Removal Act signed by Andrew Jackson", era: 2 },
  { year: 1832, event: "Worcester v. Georgia — Marshall rules for Cherokee; Jackson ignores ruling", era: 2 },
  { year: 1838, event: "Trail of Tears — 4,000+ Cherokee die on forced march", era: 2 },
  { year: 1845, event: "Southern Baptist Convention founded to defend slaveholders", era: 2 },
  { year: 1865, event: "13th Amendment — abolishes slavery 'except as punishment for crime'", era: 2 },
  { year: 1865, event: "Georgia Black Codes immediately re-enslave Black labor", era: 2 },
  { year: 1866, event: "Sherman's Field Orders No. 15 revoked — 40 Acres denied", era: 2 },
  { year: 1877, event: "Reconstruction ends — federal troops withdrawn from the South", era: 2 },
  { year: 1882, event: "Chinese Exclusion Act — first federal law to explicitly bar a racial group from immigration", era: 2 },
  { year: 1887, event: "Dawes Act — 90 million acres of Indigenous land stolen", era: 3 },
  { year: 1896, event: "Plessy v. Ferguson — 'separate but equal' enshrined in law", era: 3 },
  { year: 1898, event: "Spanish-American War — Buffalo Soldiers fight for a country that returns them to Jim Crow", era: 3 },
  { year: 1898, event: "Wilmington Massacre — only successful coup d'état in U.S. history", era: 3 },
  { year: 1909, event: "NAACP founded by Du Bois, Wells, and others", era: 3 },
  { year: 1921, event: "Tulsa Race Massacre — Greenwood District destroyed", era: 3 },
  { year: 1921, event: "Dyer Anti-Lynching Bill killed by Senate filibuster", era: 3 },
  { year: 1930, event: "Census instructions erase Black Indigenous identity", era: 3 },
  { year: 1934, event: "Indian Reorganization Act ends Dawes Act allotment", era: 3 },
  { year: 1942, event: "Bracero Program begins — 4.6 million Mexican workers exploited under conditions mirroring convict leasing", era: 3 },
  { year: 1944, event: "GI Bill — racially administered, denying benefits to Black veterans", era: 3 },
  { year: 1954, event: "Brown v. Board of Education", era: 4 },
  { year: 1955, event: "Emmett Till murdered — Sheriff Strider suppresses evidence", era: 4 },
  { year: 1963, event: "Medgar Evers assassinated in his driveway", era: 4 },
  { year: 1965, event: "Voting Rights Act passed", era: 4 },
  { year: 1967, event: "FBI COINTELPRO directive targets Black Nationalist organizations", era: 4 },
  { year: 1969, event: "Fred Hampton assassinated — FBI provides floor plan to Chicago police", era: 4 },
  { year: 1976, event: "Church Committee Report exposes COINTELPRO abuses", era: 5 },
  { year: 1990, event: "NAGPRA passed — repatriation of Indigenous remains begins", era: 5 },
  { year: 2013, event: "Shelby County v. Holder guts the Voting Rights Act", era: 5 },
  { year: 2020, event: "McGirt v. Oklahoma — Muscogee (Creek) reservation affirmed", era: 5 },
  { year: 2022, event: "Emmett Till Antilynching Act — first federal anti-lynching law, 101 years late", era: 5 },
  { year: 1935, event: "HOLC redlining maps — 'infiltration of Negro occupancy' explicitly listed as negative factor in neighborhood ratings", era: 3 },
  { year: 1968, event: "King v. Smith — Supreme Court strikes down 'man-in-the-house' rules that structurally excluded Black fathers from families", era: 4 },
  { year: 1971, event: "Nixon's War on Drugs launched — Ehrlichman later admitted it was designed to target Black communities", era: 4 },
  { year: 1986, event: "Anti-Drug Abuse Act — 100:1 crack/powder cocaine sentencing disparity; 78.7% of crack defendants were Black", era: 5 },
  { year: 1994, event: "Crime Bill — three strikes, mandatory minimums, truth-in-sentencing; 89% of federal capital prosecution defendants were Black or Hispanic", era: 5 },
  { year: 2024, event: "CoreCivic and GEO Group generate $4.38 billion in revenue; their SEC filings document financial dependence on high incarceration rates", era: 5 },
  { year: 1966, event: "Project 100,000 — McNamara drafts 354,000 men deemed unfit for service; 40.6% are Black, assigned to combat at double the casualty rate", era: 4 },
  { year: 1989, event: "Kerry Committee Report — U.S. Senate documents CIA awareness of Contra drug trafficking and deliberate inaction", era: 5 },
  { year: 1998, event: "CIA Inspector General's Report confirms CIA failed to report Contra drug trafficking to law enforcement", era: 5 },
  { year: 1968, event: "Kerner Commission Report — federal government concludes America is 'moving toward two societies, one Black, one white'; Johnson buries it", era: 4 },
  { year: 1981, event: "First AIDS cases reported — Reagan administration does not publicly acknowledge for 6 years; 41,000 die", era: 5 },
  { year: 2008, event: "Subprime mortgage crisis wipes out 53% of Black household wealth; DOJ later documents Wells Fargo targeted Black borrowers", era: 5 },
  { year: 2012, event: "Wells Fargo pays $175 million — largest fair lending settlement in DOJ history; loan officers documented calling Black borrowers 'mud people'", era: 5 },
  { year: 1921, event: "Dyer Anti-Lynching Bill passes the House 230-119 — killed by Senate filibuster; federal government had the mechanism to stop lynching and chose not to use it", era: 3 },
  { year: 1965, event: "Moynihan Report blames Black family structure for poverty without acknowledging the documented policies (redlining, man-in-the-house rules) that caused it", era: 4 },
  { year: 2021, event: "George Floyd Justice in Policing Act passes the House — killed in the Senate; the Dyer Bill pattern repeats 100 years later", era: 5 },
];
